<a href="https://colab.research.google.com/github/avanegasp/Google_Colab/blob/main/Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_de_arr = arr[0:6]

In [ ]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])